# Generated by Django 5.2.6 on 2026-04-02 00:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_follow_followed_alter_follow_follower"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="like",
            name="post",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="Follow",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
